import type { Portfolio } from "./types";

/* ============================================================================
   Real content — Sampark Bhol.
   Sources: Samparkbhol_resume_M.pdf (authoritative for résumé content),
   sampark-dev.vercel.app (npm packages, philosophy, blog articles, volunteer),
   Overleaf source (canonical external links only). CV: bundled /resume.pdf +
   Google Drive mirror.
   ========================================================================== */

const RESUME_GDRIVE = "https://drive.google.com/file/d/1Jg8omVUb4YXgC27R1Q9Oei_SHrPtWyJ1/view?usp=sharing";

export const portfolio: Portfolio = {
  profile: {
    name: "Sampark Bhol",
    handle: "@samparkbhol",
    title: "AI / ML ENGINEER",
    tagline: "Founding ML Engineer · Elsevier-published researcher. I build production-grade intelligent systems end to end — NLP, CV, predictive analytics, and quantum ML.",
    location: "India",
    avatarSprite: "/sprites/avatar.svg",
    resumeUrl: "/resume.pdf",
    socials: [
      { label: "GitHub", href: "https://github.com/SamparkBhol", icon: "github" },
      { label: "LinkedIn", href: "https://www.linkedin.com/in/sampark-bhol-118560251", icon: "linkedin" },
      { label: "Medium", href: "https://medium.com/@samparkbhol2005", icon: "medium" },
    ],
  },
  about: {
    blurb:
      "Aspiring AI & Machine Learning engineer driven by an obsessive curiosity for building production-grade intelligent systems end to end — across NLP, computer vision, predictive analytics, and quantum machine learning. Currently a Founding ML Engineer at CLR3 Ventures, architecting autonomous LLM agent pipelines, transformer similarity engines, and full ML observability stacks from the ground up. Published Elsevier researcher and active open-source contributor who reads papers cover to cover, fine-tunes frontier models for fun, and ships code that lands in production.",
    stats: [
      { label: "INTERNSHIPS", value: "4" },
      { label: "NPM PKGS", value: "3" },
      { label: "PAPERS", value: "1" },
      { label: "PROJECTS", value: "6+" },
    ],
    originStrip: [
      { caption: "Read the paper. Cover to cover.", sprite: "/sprites/origin-1.svg" },
      { caption: "Fine-tuned a frontier model. For fun.", sprite: "/sprites/origin-2.svg" },
      { caption: "Shipped it to production. It held.", sprite: "/sprites/origin-3.svg" },
    ],
    education: {
      school: "VIT Vellore",
      degree: "B.Tech, Computer Science & Engineering",
      specialization: "Specialization in Blockchain Technologies",
      period: "2022 — 2026",
      location: "Vellore, India",
      motto: "Knowledge forged in stone, sharpened on silicon.",
      notes: [
        "Distributed ledgers, smart contracts & consensus",
        "DSA · Operating Systems · DBMS · Networks",
        "Where the campaign began.",
      ],
    },
  },
  experience: [
    {
      id: "exp-1",
      role: "Founding Machine Learning Engineer (Intern)",
      org: "CLR3 Ventures (Spizen Technologies / NoLimitNodes)",
      period: "Jan 2026 — Present",
      location: "Bengaluru, India",
      level: 30,
      summary: "Building the founding ML stack — agents, recommenders, and observability — from zero.",
      highlights: [
        "Profitability prediction with ensemble gradient boosting on streaming Kafka pipelines — 92% revenue-forecast accuracy powering dynamic pricing",
        "Transformer embedding similarity engine (ANN on ClickHouse) + neural collaborative-filtering recommender at 10K+ qps in production",
        "Autonomous long-form content & synthetic-data pipeline orchestrating multi-stage LLM agents (plan → draft → summarize → validate)",
        "Founding ML infra on Kafka with Grafana drift/latency observability + CI/CD with A/B testing for safe rollouts",
      ],
      stack: ["Kafka", "ClickHouse", "LLM Agents", "Grafana", "Gradient Boosting"],
    },
    {
      id: "exp-2",
      role: "Quantum Computing & Research Intern",
      org: "QuantumX (Appetite Studio)",
      period: "Dec 2025 — Jan 2026",
      location: "Remote",
      level: 26,
      summary: "Hybrid quantum-classical ML + quantum-safe security research.",
      highlights: [
        "Hybrid quantum-classical models — variational quantum circuits + classical NNs for combinatorial optimization",
        "Quantum optimization with QAOA & VQE; investigated post-quantum cryptographic architectures for AI model integrity",
        "Authored open-source Quark (quantum-circuit semantic-similarity embeddings + QASM dedup CLI); first-authored a journal under review",
      ],
      stack: ["QAOA", "VQE", "Variational Circuits", "Python", "QASM"],
    },
    {
      id: "exp-3",
      role: "AI & ML Engineer Intern",
      org: "CSM Technologies",
      period: "May 2025 — Jul 2025",
      location: "Odisha, India",
      level: 20,
      summary: "Production RAG + transformer NLP, fine-tuned and shipped.",
      highlights: [
        "Production RAG pipelines (LangChain, LangFlow, ChromaDB, Pinecone) — +25% domain accuracy via tuned chunking & prompt engineering",
        "BERT/GPT transformer apps for classification, NER, summarization with real-time inference + vector DB integration",
        "Fine-tuned LLMs with LoRA/QLoRA — 60% less training compute; Dockerized + Kubernetes multi-service deploys",
      ],
      stack: ["LangChain", "RAG", "LoRA/QLoRA", "Docker", "Kubernetes"],
    },
    {
      id: "exp-4",
      role: "Deep Learning & Software Development Intern",
      org: "National Informatics Centre, MeitY, Govt. of India",
      period: "May 2024 — Jul 2024",
      location: "Odisha, India",
      level: 14,
      summary: "Anomaly detection & predictive modeling on 1M+ government records.",
      highlights: [
        "Anomaly detection (Isolation Forest, DBSCAN, Z-score, graph analysis) on 1M+ records — 95% precision-recall",
        "Predictive models (LogReg, SVM, Gradient Boosting, K-Means, PCA) with full EDA + feature engineering",
        "Automated ETL + warehousing in Python/SQL — 70% faster processing; dashboards adopted across departments",
      ],
      stack: ["Scikit-learn", "Python", "SQL", "ETL", "Matplotlib"],
    },
  ],
  projects: [
    {
      id: "proj-cairn",
      name: "CAIRN",
      tagline: "Autonomous LLM experiment runner",
      hp: 100,
      difficulty: "BOSS",
      description:
        "An autonomous experiment runner letting LLM coding agents iteratively improve a codebase while keeping a persistent wiki of every attempt. Python daemon over msgpack RPC with SQLite WAL state, git-worktree isolation, hard budget caps, and an anti-Goodhart holdout evaluator — covered by 67+ tests.",
      year: "2026",
      tags: ["Python", "msgpack RPC", "SQLite", "Git Worktrees", "LLM Agents"],
      sprite: "/sprites/proj-1.svg",
      links: [{ label: "CODE", href: "https://github.com/SamparkBhol/Cairn" }],
    },
    {
      id: "proj-browser-llm",
      name: "BROWSER-LLM",
      tagline: "Offline AI chatbot in the browser",
      hp: 92,
      difficulty: "BOSS",
      description:
        "Fully client-side AI chatbot with WebGPU hardware acceleration — sub-second token latency, zero backend, complete on-device privacy. Runs quantized GGUF & ONNX models via lazy weight streaming, KV-cache management, and memory-efficient attention on consumer hardware.",
      year: "2025",
      tags: ["JavaScript", "WebGPU", "WebAssembly", "Transformers.js"],
      sprite: "/sprites/proj-2.svg",
      links: [
        { label: "LIVE", href: "https://browser-llm-three.vercel.app/" },
        { label: "CODE", href: "https://github.com/SamparkBhol/Browser---llm" },
      ],
    },
    {
      id: "proj-datawiz",
      name: "DATAWIZ-PRO",
      tagline: "AI-powered AutoML analytics platform",
      hp: 84,
      difficulty: "HARD",
      description:
        "AutoML analytics platform with Bayesian hyperparameter tuning, automated feature/model selection across regression, classification, and clustering. End-to-end CSV/JSON/SQL ingestion with automated preprocessing, outlier detection, and interactive BI dashboards for non-technical stakeholders.",
      year: "2025",
      tags: ["Python", "React", "Scikit-learn", "Plotly", "FastAPI"],
      sprite: "/sprites/proj-3.svg",
      links: [
        { label: "LIVE", href: "https://data-wiz-pro.vercel.app/" },
        { label: "CODE", href: "https://github.com/SamparkBhol/DataWiz-Pro" },
      ],
    },
    {
      id: "proj-leafguard",
      name: "LEAFGUARD AI",
      tagline: "Client-side plant-disease diagnosis",
      hp: 64,
      difficulty: "NORMAL",
      description:
        "Plant-disease diagnosis web app with a React frontend and TensorFlow.js for client-side CNN inference — real-time agricultural AI assistance with no server round-trip.",
      year: "2024",
      tags: ["React", "TensorFlow.js", "CNN", "Computer Vision", "FastAPI"],
      sprite: "/sprites/proj-4.svg",
      links: [{ label: "GITHUB", href: "https://github.com/SamparkBhol" }],
    },
    {
      id: "proj-assignofast",
      name: "ASSIGNOFAST",
      tagline: "Offline-first student assignment app",
      hp: 52,
      difficulty: "NORMAL",
      description:
        "Smart assignment-management app for students — syncs assignments and timetables from Firebase while supporting full offline access via SQLite.",
      year: "2024",
      tags: ["Flutter", "Firebase", "SQLite", "Kotlin", "Swift"],
      sprite: "/sprites/proj-5.svg",
      links: [{ label: "GITHUB", href: "https://github.com/SamparkBhol" }],
    },
  ],
  packages: [
    {
      id: "pkg-cli-legend",
      name: "cli-legend",
      description: "A fun command-line roguelike dungeon game — ASCII graphics, turn-based combat, inventory.",
      version: "1.0.0",
      weeklyDownloads: 1200,
      installCmd: "npm i cli-legend",
      href: "https://www.npmjs.com/package/cli-legend",
      tags: ["cli", "roguelike", "game"],
    },
    {
      id: "pkg-gamedev-utils",
      name: "gamedev-simple-utils",
      description: "A simple utility package for game development.",
      version: "1.0.0",
      weeklyDownloads: 300,
      installCmd: "npm i gamedev-simple-utils",
      href: "https://www.npmjs.com/package/gamedev-simple-utils",
      tags: ["gamedev", "utils"],
    },
    {
      id: "pkg-dev-toolkit",
      name: "dev-toolkit-sampark",
      description: "A Gen-Z-inspired CLI toolkit for modern developers — from linting gently to shipping fast.",
      version: "1.0.0",
      weeklyDownloads: 250,
      installCmd: "npm i dev-toolkit-sampark",
      href: "https://www.npmjs.com/package/dev-toolkit-sampark",
      tags: ["cli", "toolkit", "dx"],
    },
  ],
  research: [
    {
      id: "res-wsn",
      title: "An Energy-Efficient Hybrid Communication Protocol for Large-Area Wireless Sensor Networks",
      venue: "Elsevier Procedia Computer Science (ICECMSN)",
      year: "2025",
      authors: ["Sampark Bhol"],
      abstract:
        "A novel energy-efficient hybrid routing protocol for wireless sensor networks, delivering significant efficiency improvements for large-scale IoT deployments through optimized cluster-head selection and data-aggregation strategies.",
      links: [{ label: "PUBLISHED", href: "https://www.sciencedirect.com/science/article/pii/S1877050925000596" }],
    },
    {
      id: "res-quantum",
      title: "Hybrid Classical and Quantum Query Complexity for Hypothesis Verification Under Structured Priors and Bounded Phase Noise",
      venue: "Under review · in collab with QuantumX",
      year: "2026",
      authors: ["Sampark Bhol"],
      abstract:
        "First-authored research on hybrid classical–quantum query complexity for hypothesis verification under structured priors and bounded phase noise — developed during the QuantumX internship alongside the open-source Quark library. Currently under review for publication.",
      links: [{ label: "QUARK REPO", href: "https://github.com/SamparkBhol/quark" }],
    },
  ],
  blogs: [
    {
      slug: "neurosymbolic-ai-a-view",
      title: "NeuroSymbolic AI: A View",
      excerpt: "Integrating neural networks with symbolic reasoning — can hybrid models overcome the limits of purely data-driven or rule-based AI?",
      date: "2024-11-01",
      readingMins: 8,
      tags: ["AI Research"],
      cover: "/sprites/blog-1.svg",
    },
    {
      slug: "quantum-enhanced-nlp",
      title: "Quantum-Enhanced NLP: The Future of Cloud AI",
      excerpt: "How quantum computing could revolutionize NLP tasks like sentiment analysis and translation in the cloud.",
      date: "2024-10-15",
      readingMins: 7,
      tags: ["Quantum Computing"],
      cover: "/sprites/blog-2.svg",
    },
    {
      slug: "cern-in-october",
      title: "CERN in October: A Month of Milestones and Marvels",
      excerpt: "A recap of significant achievements, experiments, and groundbreaking discoveries at CERN during a pivotal month.",
      date: "2024-10-31",
      readingMins: 6,
      tags: ["Physics"],
      cover: "/sprites/blog-3.svg",
    },
    {
      slug: "quantum-driven-gaming",
      title: "Quantum-Driven Gaming: AI Meets the Future",
      excerpt: "Exploring the intersection of quantum computing, AI, and the future of gaming at the cusp of a new tech era.",
      date: "2024-09-20",
      readingMins: 6,
      tags: ["Gaming & AI"],
      cover: "/sprites/blog-4.svg",
    },
  ],
  volunteer: [
    {
      id: "vol-1",
      role: "AI/ML Lead",
      org: "IEEE Computer Society, VIT",
      period: "2023 — 2025",
      summary: "Led the AI/ML wing — events, workshops, and community projects.",
      impact: ["Organized hackathons with 200+ participants", "Ran DL / NLP / CV workshops for students"],
    },
    {
      id: "vol-2",
      role: "Member",
      org: "Association of Energy Engineers",
      period: "2023 — 2024",
      summary: "Active member contributing to energy-efficiency and sustainability initiatives.",
      impact: ["Energy-efficiency research community", "Sustainability-focused collaboration"],
    },
  ],
  skills: [
    {
      name: "Languages",
      skills: [
        { name: "Python", level: 95, category: "Languages" },
        { name: "JavaScript", level: 84, category: "Languages" },
        { name: "TypeScript", level: 82, category: "Languages" },
        { name: "SQL", level: 85, category: "Languages" },
        { name: "R", level: 70, category: "Languages" },
        { name: "Golang", level: 68, category: "Languages" },
        { name: "Solidity", level: 60, category: "Languages" },
        { name: "HTML5", level: 88, category: "Languages" },
        { name: "CSS3", level: 86, category: "Languages" },
      ],
    },
    {
      name: "AI / ML & Deep Learning",
      skills: [
        { name: "PyTorch", level: 92, category: "AI / ML & Deep Learning" },
        { name: "TensorFlow", level: 88, category: "AI / ML & Deep Learning" },
        { name: "Scikit-learn", level: 90, category: "AI / ML & Deep Learning" },
        { name: "Keras", level: 84, category: "AI / ML & Deep Learning" },
        { name: "XGBoost", level: 82, category: "AI / ML & Deep Learning" },
        { name: "LightGBM", level: 80, category: "AI / ML & Deep Learning" },
        { name: "Hugging Face", level: 88, category: "AI / ML & Deep Learning" },
        { name: "OpenCV", level: 78, category: "AI / ML & Deep Learning" },
        { name: "MediaPipe", level: 72, category: "AI / ML & Deep Learning" },
        { name: "FAISS", level: 80, category: "AI / ML & Deep Learning" },
        { name: "GANs", level: 72, category: "AI / ML & Deep Learning" },
        { name: "Reinforcement Learning", level: 70, category: "AI / ML & Deep Learning" },
      ],
    },
    {
      name: "NLP / GenAI",
      skills: [
        { name: "LangChain", level: 90, category: "NLP / GenAI" },
        { name: "LangGraph", level: 82, category: "NLP / GenAI" },
        { name: "LangFlow", level: 80, category: "NLP / GenAI" },
        { name: "Haystack", level: 74, category: "NLP / GenAI" },
        { name: "RAG Pipelines", level: 90, category: "NLP / GenAI" },
        { name: "Prompt Engineering", level: 88, category: "NLP / GenAI" },
        { name: "Fine-Tuning (LoRA/QLoRA)", level: 85, category: "NLP / GenAI" },
        { name: "BERT / GPT", level: 86, category: "NLP / GenAI" },
        { name: "Sentence Transformers", level: 82, category: "NLP / GenAI" },
        { name: "Semantic Search", level: 84, category: "NLP / GenAI" },
        { name: "spaCy / NLTK", level: 78, category: "NLP / GenAI" },
      ],
    },
    {
      name: "Data Science & Analytics",
      skills: [
        { name: "Pandas", level: 92, category: "Data Science & Analytics" },
        { name: "NumPy", level: 90, category: "Data Science & Analytics" },
        { name: "SciPy", level: 80, category: "Data Science & Analytics" },
        { name: "Matplotlib", level: 86, category: "Data Science & Analytics" },
        { name: "Seaborn", level: 82, category: "Data Science & Analytics" },
        { name: "Plotly", level: 82, category: "Data Science & Analytics" },
        { name: "A/B Testing", level: 78, category: "Data Science & Analytics" },
        { name: "Bayesian Inference", level: 76, category: "Data Science & Analytics" },
        { name: "Feature Engineering", level: 86, category: "Data Science & Analytics" },
        { name: "Time Series", level: 76, category: "Data Science & Analytics" },
        { name: "PowerBI", level: 72, category: "Data Science & Analytics" },
        { name: "Tableau", level: 70, category: "Data Science & Analytics" },
      ],
    },
    {
      name: "MLOps & Infrastructure",
      skills: [
        { name: "Docker", level: 84, category: "MLOps & Infrastructure" },
        { name: "Kubernetes", level: 78, category: "MLOps & Infrastructure" },
        { name: "MLflow", level: 78, category: "MLOps & Infrastructure" },
        { name: "Kubeflow", level: 70, category: "MLOps & Infrastructure" },
        { name: "Weights & Biases", level: 76, category: "MLOps & Infrastructure" },
        { name: "GitHub Actions", level: 80, category: "MLOps & Infrastructure" },
        { name: "Apache Spark", level: 74, category: "MLOps & Infrastructure" },
        { name: "Kafka", level: 80, category: "MLOps & Infrastructure" },
        { name: "Apache Airflow", level: 74, category: "MLOps & Infrastructure" },
        { name: "ETL / ELT", level: 80, category: "MLOps & Infrastructure" },
        { name: "DVC", level: 70, category: "MLOps & Infrastructure" },
      ],
    },
    {
      name: "Databases & Cloud",
      skills: [
        { name: "PostgreSQL", level: 82, category: "Databases & Cloud" },
        { name: "MySQL", level: 82, category: "Databases & Cloud" },
        { name: "MongoDB", level: 80, category: "Databases & Cloud" },
        { name: "Redis", level: 74, category: "Databases & Cloud" },
        { name: "ClickHouse", level: 76, category: "Databases & Cloud" },
        { name: "Pinecone", level: 82, category: "Databases & Cloud" },
        { name: "Weaviate", level: 74, category: "Databases & Cloud" },
        { name: "ChromaDB", level: 84, category: "Databases & Cloud" },
        { name: "Elasticsearch", level: 72, category: "Databases & Cloud" },
        { name: "AWS", level: 78, category: "Databases & Cloud" },
        { name: "GCP (Vertex AI)", level: 72, category: "Databases & Cloud" },
        { name: "Terraform", level: 68, category: "Databases & Cloud" },
      ],
    },
    {
      name: "Web & Tools",
      skills: [
        { name: "React", level: 82, category: "Web & Tools" },
        { name: "Node.js", level: 78, category: "Web & Tools" },
        { name: "Flask", level: 80, category: "Web & Tools" },
        { name: "Django", level: 74, category: "Web & Tools" },
        { name: "FastAPI", level: 86, category: "Web & Tools" },
        { name: "Three.js", level: 70, category: "Web & Tools" },
        { name: "Flutter", level: 74, category: "Web & Tools" },
        { name: "WebGPU", level: 74, category: "Web & Tools" },
        { name: "WebAssembly", level: 70, category: "Web & Tools" },
        { name: "Streamlit", level: 80, category: "Web & Tools" },
        { name: "Gradio", level: 78, category: "Web & Tools" },
        { name: "Ollama", level: 78, category: "Web & Tools" },
        { name: "MCP", level: 76, category: "Web & Tools" },
      ],
    },
  ],
  certifications: [
    {
      id: "cert-oracle-genai",
      title: "Oracle Generative AI Cloud Infrastructure Professional",
      issuer: "Oracle",
      year: "2025",
      icon: "🏆",
      rarity: "LEGENDARY",
      credentialUrl: "https://drive.google.com/file/d/10oyQhf3rD7HnHv3NYwNhy9JIWIdrOZ24/view",
    },
    {
      id: "cert-nvidia",
      title: "NVIDIA: Building Transformer-Based NLP Applications",
      issuer: "NVIDIA",
      year: "2025",
      icon: "🎖️",
      rarity: "EPIC",
      credentialUrl: "https://drive.google.com/file/d/15jOc2py2i3BwMSgGT2Dsea2fR0EesIMb/view",
    },
    {
      id: "cert-ibm",
      title: "IBM Deep Learning Fundamentals",
      issuer: "IBM (Cognitive Class)",
      year: "2024",
      icon: "🥇",
      rarity: "RARE",
      credentialUrl: "https://courses.cognitiveclass.ai/certificates/2752886f81c445d3b1e6a260dd508b57",
    },
    {
      id: "cert-saviynt",
      title: "ISAA Saviynt Identity Security",
      issuer: "Saviynt",
      year: "2024",
      icon: "🥈",
      rarity: "COMMON",
      credentialUrl: "https://drive.google.com/file/d/1JIiLKb4FZheMo9TkICBUj9YOqX0DkC70/view",
    },
    {
      id: "cert-oracle-assoc",
      title: "Oracle Cloud Infrastructure Associate",
      issuer: "Oracle",
      year: "2025",
      icon: "🥈",
      rarity: "COMMON",
      credentialUrl: "https://drive.google.com/file/d/10oyQhf3rD7HnHv3NYwNhy9JIWIdrOZ24/view",
    },
  ],
  contact: {
    email: "samparkaccess1234@gmail.com",
    blurb: "Available for work and collaboration. Got a quest? Insert coin and say hello.",
    formAction: RESUME_GDRIVE,
    socials: [
      { label: "GitHub", href: "https://github.com/SamparkBhol", icon: "github" },
      { label: "LinkedIn", href: "https://www.linkedin.com/in/sampark-bhol-118560251", icon: "linkedin" },
      { label: "Email", href: "mailto:samparkaccess1234@gmail.com", icon: "mail" },
    ],
  },
};
