import type { Resume } from "./types";

/* ============================================================================
   The single source of truth. Every number on the site must appear here.
   Role bullets are the résumé wording, verbatim; the Helmit runtime bullet is
   split across two panels (RUNTIME / DATA) at its comma.
   ========================================================================== */

export const resume: Resume = {
  profile: {
    name: "Sampark Bhol",
    title: "Software Engineer",
    classLine: "Backend systems · ML · LLM agents · games · mobile",
    employer: "Helmit",
    location: "Munich, Germany / remote from India",
    since: "Aug 2026",
    premise: "A comic about the things I've built.",
    narration:
      "I build backend systems, ML pipelines, LLM agents, mobile apps and games. This issue is my portfolio: five stages, nine bosses, a shop, an arcade and a library. Open it, flip it, or press R for the plain résumé.",
    email: "samparkaccess1234@gmail.com",
    github: "https://github.com/SamparkBhol",
    linkedin: "https://www.linkedin.com/in/sampark-bhol-118560251",
    medium: "https://medium.com/@samparkbhol2005",
    cvUrl: "/cv.pdf",
    cvMirrorUrl: "https://drive.google.com/file/d/1Jg8omVUb4YXgC27R1Q9Oei_SHrPtWyJ1/view?usp=sharing",
    siteUrl: "https://sampark-dev.vercel.app",
    issue: { number: 1, month: "September 2026", price: "Free", title: "SAMPARK BHOL", volume: "Vol. 1" },
  },

  roles: [
    {
      id: "helmit",
      org: "Helmit",
      title: "Software Engineer",
      period: "Aug 2026 – present",
      location: "Munich, Germany / remote, India",
      current: true,
      tone: 0,
      stack: ["Java", "Spring Boot", "Go", "TypeScript", "Python", "gRPC", "AWS", "GCP", "GKE Autopilot", "Redis", "PostgreSQL", "Vertex AI", "OpenTelemetry", "React Native", "Expo", "Swift"],
      classes: ["software"],
      flow: {
        traveller: "a request",
        caption: "ONE REQUEST, CLIENT TO PHONE",
        stamp: "200 OK",
        stampNote: "the request returns",
        burst: { after: 5, within: 4, label: "HPA · 3 → 8 replicas" },
        nodes: [
          { id: "clients", glyph: "clients", label: "9 client platforms", fact: "9 platform integrations over OAuth2, MTProto and push-model data portability, one reverse-engineered from its rejection responses.", log: "client → gateway · oauth2", panel: "panel-integrations" },
          { id: "gate", glyph: "gate", label: "WAF · gateway", fact: "API gateway routing and WAF edge policies, least-privilege IAM, Secret Manager-backed configuration.", log: "gateway waf=pass → api", panel: "panel-delivery" },
          { id: "pods", glyph: "pods", label: "GKE Autopilot", fact: "Horizontal pod autoscaling, disruption budgets and leader-election sharding; the service scaled from 3 to 8 replicas.", log: "pod (leader) · go / typescript service", panel: "panel-runtime" },
          { id: "queue", glyph: "queue", label: "Redis queues", fact: "Redis job queues for asynchronous, idempotent processing.", log: "redis job enqueued · async", panel: "panel-services" },
          { id: "db", glyph: "database", label: "PostgreSQL · 58", fact: "PostgreSQL across 58 schema migrations.", log: "postgres schema v058 · 58 migrations", panel: "panel-data" },
          { id: "agent", glyph: "agent", label: "Vertex AI agent", fact: "A tool-calling LLM agent with an argument-resolved permission model, OpenTelemetry tracing and a static data-quarantine boundary.", log: "agent tool permitted from args · otel span", panel: "panel-agent" },
          { id: "phone", glyph: "phone", label: "React Native app", fact: "React Native and Expo client with native iOS Screen Time and Family Controls bridges; en/de localization.", log: "phone push delivered · en/de", panel: "panel-mobile" },
        ],
      },
      panels: [
        {
          id: "services",
          label: "Services",
          span: 5,
          thumb: "idem",
          tags: ["Java", "Spring Boot", "Go", "TypeScript", "Python", "gRPC", "AWS", "GCP"],
          text: "Design, develop, test and maintain applications and microservices using Java and Spring Boot, Go and TypeScript on AWS and GCP, owning REST API contracts, request validation, asynchronous processing, idempotent operations and reliable state transitions across a distributed application design serving iOS and Android clients.",
        },
        {
          id: "reliability",
          label: "Reliability",
          span: 4,
          text: "Support application performance, reliability, resilience and operational readiness with structured logging, service metrics, health checks, timeout propagation, retry policies, backpressure and graceful degradation, and resolve production defects across application, service, network and relational database layers using latency, error-rate and saturation signals.",
        },
        {
          id: "delivery",
          label: "Delivery & security",
          span: 3,
          tags: ["GitHub Actions", "Cloud Build", "Secret Manager", "IAM", "WAF"],
          text: "Contribute to CI/CD pipelines and automated deployments with GitHub Actions and Cloud Build pre-deploy gates covering build, vet, test and dependency freshness, applying DevSecOps practices through Secret Manager-backed configuration, least-privilege IAM, API gateway routing and WAF edge policies to keep services secure, scalable and maintainable.",
        },
        {
          id: "runtime",
          label: "Runtime",
          span: 3,
          thumb: "pods",
          tags: ["GKE Autopilot", "HPA", "PDB"],
          text: "Operate containerized Kubernetes (GKE Autopilot) workloads with horizontal pod autoscaling, disruption budgets and a leader-election sharding pattern that lets replicas divide ownership of live platform connections.",
        },
        {
          id: "data",
          label: "Data",
          span: 4,
          numeral: "58",
          tags: ["Redis", "PostgreSQL"],
          text: "Backed by Redis job queues and PostgreSQL across 58 schema migrations.",
        },
        {
          id: "integrations",
          label: "Integrations",
          span: 5,
          numeral: "9",
          thumb: "ladder",
          tags: ["OAuth2", "MTProto", "push data portability"],
          text: "Delivered 9 platform integrations end to end across OAuth2, MTProto and push-model data portability flows, including an undocumented third-party API reverse-engineered from its rejection responses and stabilised with a retry-and-drop strategy.",
        },
        {
          id: "agent",
          label: "The agent",
          span: 7,
          thumb: "quarantine",
          tags: ["Vertex AI", "OpenTelemetry", "tool calling"],
          text: "Built a tool-calling LLM agent on Vertex AI with an argument-resolved permission model, OpenTelemetry distributed tracing across the router, skill-selection and tool-execution loop, and a statically enforced data-quarantine boundary keeping untrusted content away from tool execution.",
        },
        {
          id: "mobile",
          label: "Mobile",
          span: 5,
          tags: ["React Native", "Expo", "Swift", "Sentry", "PostHog", "Firebase"],
          text: "Contribute to the React Native and Expo mobile client with native iOS Screen Time and Family Controls integrations through custom Swift bridges, alongside Sentry, PostHog, Firebase and attribution instrumentation and en/de localization built as infrastructure rather than hardcoded strings across a live chat UI.",
        },
      ],
    },
    {
      id: "clr3",
      org: "CLR3 Ventures",
      orgNote: "Spizen Technologies",
      title: "Founding Machine Learning Engineer 1",
      period: "Jan 2026 – Aug 2026",
      location: "Bengaluru, India",
      tone: 10,
      stack: ["Kafka", "ClickHouse", "Redis", "Grafana", "gradient boosting", "transformers", "LLM agents", "GitHub Actions"],
      classes: ["ml", "software"],
      flow: {
        traveller: "an event",
        caption: "ONE EVENT, STREAM TO PRICE",
        stamp: "92%",
        stampNote: "revenue-forecast accuracy",
        nodes: [
          { id: "stream", glyph: "stream", label: "Kafka stream", fact: "Event-driven Apache Kafka streaming feature pipelines.", log: "kafka event consumed", panel: "panel-profit" },
          { id: "features", glyph: "features", label: "feature store", fact: "SQL feature stores with Redis caching.", log: "features joined · redis cache hit", panel: "panel-infra" },
          { id: "model", glyph: "model", label: "gradient boosting", fact: "Ensemble gradient boosting profitability model reaching 92% accuracy on revenue forecasts.", log: "model scored · 92% accuracy", panel: "panel-profit" },
          { id: "price", glyph: "price", label: "dynamic pricing", fact: "Dynamic pricing across business verticals.", log: "price updated", panel: "panel-profit" },
          { id: "vectors", glyph: "vectors", label: "ANN on ClickHouse", fact: "A transformer embedding similarity engine with approximate nearest neighbour search on ClickHouse.", log: "ann neighbours found · clickhouse", panel: "panel-similarity" },
          { id: "recommender", glyph: "recommender", label: "neural CF", fact: "A neural collaborative filtering recommender serving 10K+ queries per second.", log: "recommendations served · 10K+ qps", panel: "panel-similarity" },
          { id: "api", glyph: "api", label: "REST · Grafana", fact: "Served behind REST APIs with Grafana drift and latency monitoring, CI/CD and A/B model rollouts.", log: "response ok · grafana green", panel: "panel-infra" },
        ],
      },
      panels: [
        {
          id: "profit",
          label: "Profitability model",
          span: 7,
          numeral: "92%",
          text: "Built a profitability prediction system with ensemble gradient boosting over event-driven Kafka streaming feature pipelines, reaching 92% accuracy on revenue forecasts and powering dynamic pricing across business verticals.",
        },
        {
          id: "similarity",
          label: "Similarity engine",
          span: 5,
          numeral: "10K+",
          text: "Shipped a transformer embedding similarity engine with approximate nearest neighbour search on ClickHouse and a neural collaborative filtering recommender serving 10K+ queries per second in production behind REST APIs.",
        },
        {
          id: "pipeline",
          label: "Content pipeline",
          span: 5,
          text: "Architected an autonomous content and synthetic data generation pipeline orchestrating multi-stage LLM agents through planning, drafting, summarization and validation, with retrieval-based deduplication and policy-aware filtering.",
        },
        {
          id: "infra",
          label: "Founding ML infrastructure",
          span: 7,
          text: "Established the founding ML infrastructure on Apache Kafka for event-driven streaming, with Redis caching, SQL feature stores, Grafana dashboards for observability, model drift detection and inference latency, plus GitHub Actions CI/CD pipelines with A/B testing for safe model rollouts.",
        },
      ],
    },
    {
      id: "quantumx",
      org: "QuantumX",
      orgNote: "Appetite Studio",
      title: "Quantum Computing & Research Intern",
      period: "Nov 2025 – Jan 2026",
      location: "Remote",
      tone: 25,
      stack: ["QAOA", "VQE", "variational circuits", "Python", "QASM", "Neon PostgreSQL", "RabbitMQ"],
      classes: ["research", "software"],
      flow: {
        traveller: "a circuit",
        caption: "ONE CIRCUIT, QASM TO VECTOR",
        stamp: "OPEN SOURCE",
        stampNote: "quark, with QuantumX",
        nodes: [
          { id: "circuit", glyph: "circuit", label: "QASM circuit", fact: "Variational quantum circuits paired with classical neural networks for combinatorial optimization.", log: "circuit parsed · qasm", panel: "panel-qx" },
          { id: "embedding", glyph: "embedding", label: "quark embedding", fact: "quark: an open-source library learning semantic embeddings over QASM circuits.", log: "embedding computed · quark", panel: "panel-qx" },
          { id: "neon", glyph: "database", label: "Neon PostgreSQL", fact: "Embeddings stored on Neon PostgreSQL.", log: "vector stored · neon", panel: "panel-qx" },
          { id: "rabbit", glyph: "rabbit", label: "RabbitMQ", fact: "RabbitMQ carries the dedup jobs between services.", log: "job queued · rabbitmq", panel: "panel-qx" },
          { id: "dedupe", glyph: "dedupe", label: "dedup CLI", fact: "A CLI that points at a folder of QASM files and reports which ones are duplicates.", log: "duplicates grouped", panel: "panel-qx" },
          { id: "optimizer", glyph: "optimizer", label: "QAOA · VQE", fact: "QAOA and VQE optimization protocols; post-quantum cryptography evaluated for model integrity.", log: "qaoa converged", panel: "panel-qx" },
        ],
      },
      panels: [
        {
          id: "qx",
          label: "Hybrid quantum ML",
          span: 12,
          text: "Researched hybrid quantum-classical models pairing variational quantum circuits with neural networks for combinatorial optimization, designing QAOA and VQE protocols and evaluating post-quantum cryptography, and authored quark, an open-source library learning semantic embeddings over QASM circuits on Neon PostgreSQL and RabbitMQ; first-authored a journal paper on quantum-enhanced machine learning, now under review.",
        },
      ],
    },
    {
      id: "csm",
      org: "CSM Technologies",
      title: "AI & ML Engineer Intern",
      period: "May 2025 – Jul 2025",
      location: "Odisha, India",
      tone: 25,
      stack: ["LangChain", "RAG", "LoRA/QLoRA", "Docker", "Kubernetes"],
      classes: ["ml"],
      flow: {
        traveller: "a question",
        caption: "ONE QUESTION, DOCUMENT TO ANSWER",
        stamp: "+25%",
        stampNote: "domain accuracy",
        nodes: [
          { id: "documents", glyph: "documents", label: "documents", fact: "Domain documents, chunked with tuned strategies.", log: "documents loaded", panel: "panel-csm1" },
          { id: "chunks", glyph: "chunks", label: "chunking", fact: "Chunking, prompt and retrieval tuning lifted domain accuracy by 25%.", log: "chunks embedded", panel: "panel-csm1" },
          { id: "vectordb", glyph: "vectordb", label: "ChromaDB · Pinecone", fact: "Vector stores: ChromaDB and Pinecone, with LangChain and LangFlow.", log: "top-k retrieved", panel: "panel-csm1" },
          { id: "llm", glyph: "llm", label: "LoRA-tuned LLM", fact: "LLMs fine-tuned with LoRA and QLoRA at 60% less training compute, at parity with full fine-tuning.", log: "generation · lora adapter", panel: "panel-csm1" },
          { id: "answer", glyph: "answer", label: "answer · k8s", fact: "BERT and GPT services for classification, NER and summarization, containerized with Docker and deployed on Kubernetes.", log: "answer served · kubernetes", panel: "panel-csm1" },
        ],
      },
      panels: [
        {
          id: "csm1",
          label: "Production RAG",
          span: 12,
          text: "Shipped production RAG pipelines with LangChain, LangFlow, ChromaDB and Pinecone, lifting domain accuracy by 25% through chunking and prompt tuning; built BERT and GPT-class transformer applications; fine-tuned LLMs with LoRA and QLoRA at 60% less training compute, containerized with Docker and deployed on Kubernetes.",
        },
      ],
    },
    {
      id: "nic",
      org: "National Informatics Centre, MeitY",
      orgNote: "Government of India",
      title: "Deep Learning & Software Development Intern",
      period: "May 2024 – Jul 2024",
      location: "Odisha, India",
      tone: 25,
      stack: ["scikit-learn", "Python", "SQL", "ETL"],
      classes: ["ml", "research"],
      flow: {
        traveller: "a record",
        caption: "ONE RECORD, RAW TO DASHBOARD",
        stamp: "95%",
        stampNote: "precision and recall",
        nodes: [
          { id: "records", glyph: "records", label: "1M+ records", fact: "Government datasets of 1M+ records.", log: "record ingested", panel: "panel-nic1" },
          { id: "etl", glyph: "etl", label: "ETL · Python / SQL", fact: "Automated ETL and warehousing with schema validation and quality profiling; processing time cut by 70%.", log: "schema validated · warehoused", panel: "panel-nic1" },
          { id: "forest", glyph: "forest", label: "Isolation Forest · DBSCAN", fact: "Anomaly detection with Isolation Forest, DBSCAN, z-score statistics and graph analysis.", log: "anomaly scored", panel: "panel-nic1" },
          { id: "alerts", glyph: "alerts", label: "anomalies · 95%", fact: "95% precision and recall on irregular-pattern identification; predictive models with Logistic Regression, SVM, K-Means and PCA.", log: "flagged · 95% precision-recall", panel: "panel-nic1" },
          { id: "dashboard", glyph: "dashboard", label: "dashboards", fact: "Matplotlib, Seaborn and Plotly dashboards adopted across government departments.", log: "dashboard updated", panel: "panel-nic1" },
        ],
      },
      panels: [
        {
          id: "nic1",
          label: "Anomaly detection at scale",
          span: 12,
          text: "Built anomaly detection with Isolation Forest, DBSCAN, z-score statistics and graph analysis on 1M+ government records at 95% precision-recall; predictive models with full EDA and feature engineering; automated ETL and warehousing in Python and SQL, cutting processing time by 70% and shipping dashboards adopted across departments.",
        },
      ],
    },
  ],

  projects: [
    {
      id: "cairn",
      name: "Cairn",
      stamp: "AGENTS / MEMORY",
      vs: "forgetting",
      idea: "An autonomous experiment runner that remembers what it tried. Karpathy's autoresearch loop hits a wall after about forty experiments: the agent starts re-proposing what it already tried. Cairn keeps a wiki as memory, so every kept experiment is a stone on the trail.",
      system: "A Python daemon and a thin client over msgpack-framed RPC on a Unix socket; SQLite in WAL mode as the source of truth for the queue, runs, budget and baseline; every experiment in a throwaway git worktree; hard caps on experiments, wallclock and cost; a two-gear explore/consolidate loop; an anti-Goodhart holdout evaluator in a fresh worktree every Nth run; 67+ regression tests.",
      result: "Come back in a few hours to better code in small reviewable commits, a wiki that says why it is better, and a log of every run, including the ones that failed.",
      stack: ["Python", "msgpack RPC", "SQLite WAL", "git worktrees", "LLM agents"],
      year: "2026",
      links: { code: "https://github.com/SamparkBhol/Cairn" },
      featured: true,
      accent: "#FFD23F",
      glyph: "cairn",
    },
    {
      id: "shadow-agent",
      name: "Shadow-agent",
      stamp: "TERMINAL / ON-DEVICE",
      vs: "the blank prompt",
      idea: "A terminal that learns how you work and predicts your next command, entirely on your device. It learns your hands. Nothing leaves your machine.",
      system: "Two models side by side in the browser: a variable-order Markov chain over command sequences, synchronous on every keystroke, and a MiniLM sentence-embedding model in a Web Worker on WebGPU with a WASM fallback; a ranking step blends them; everything learned persists in IndexedDB; the terminal itself is a sandboxed simulator with a virtual filesystem and stand-ins for git, npm, docker and curl.",
      result: "Inline suggestions that never lag behind typing, no inference server, no telemetry, optional AES-GCM-encrypted sync between devices.",
      stack: ["Next.js", "TypeScript", "xterm.js", "Transformers.js", "WebGPU"],
      year: "2026",
      links: { live: "https://shadow-agent.vercel.app/", code: "https://github.com/SamparkBhol/Shadow-agent" },
      featured: true,
      accent: "#7CE0A5",
      glyph: "terminal",
    },
    {
      id: "browser-llm",
      name: "Browser-LLM",
      stamp: "WEBGPU / OFFLINE",
      vs: "the round trip",
      idea: "A fully client-side chatbot: WebGPU acceleration, zero backend, complete on-device privacy.",
      system: "Quantized GGUF and ONNX models through Transformers.js with lazy weight streaming, KV-cache management and memory-efficient attention on consumer hardware; a progressive web app with conversation history, model switching and adaptive inference settings that trade quality for speed per device.",
      result: "Sub-second token latency with nothing leaving the device.",
      stack: ["JavaScript", "WebGPU", "WebAssembly", "Transformers.js"],
      year: "2025",
      links: { live: "https://browser-llm-three.vercel.app/", code: "https://github.com/SamparkBhol/Browser---llm" },
      featured: true,
      accent: "#8FD3FF",
      glyph: "browser",
    },
    {
      id: "quark",
      name: "quark",
      stamp: "QUANTUM / EMBEDDINGS",
      vs: "duplicate circuits",
      idea: "Quantum programs can be written many ways and still compute the same unitary, and checking that exactly is exponential. quark turns each circuit into a vector so equivalent ones land close and unrelated ones sit near zero.",
      system: "A 647k-parameter PyTorch model trained on circuits and the rewrites that should be equivalent; plugs into Qiskit and PennyLane; ships a pretrained model and a CLI that points at a folder of QASM files and reports duplicates; an exact unitary verifier for up to about ten qubits when you need a proof.",
      result: "Embedding about a thousand small circuits takes a second on a CPU. Open source, and presented at FITT, IIT Delhi.",
      stack: ["Python", "PyTorch", "Qiskit", "PennyLane", "QASM"],
      year: "2026",
      links: { live: "https://quark.quantumx.technology/", code: "https://github.com/SamparkBhol/quark" },
      featured: true,
      accent: "#C7B8EA",
      glyph: "quark",
    },
    {
      id: "secfix",
      name: "SecFix",
      stamp: "SECURITY / AGENT",
      vs: "silent vulnerabilities",
      idea: "An autonomous secure-coding agent. It reads source code, finds real vulnerabilities with a language model, rewrites the affected files, then re-audits its own patch as an independent reviewer.",
      system: "A perceive, reason, act, verify loop per file: overlapping windows for large sources, findings with CWE and OWASP mapping and severity, whole-file rewrites that preserve signatures, patches parsed with the language's own toolchain and re-audited by the model, up to a configurable number of rounds; files in parallel; any OpenAI-compatible endpoint including local Ollama; an optional cross-file vector index and an MCP server.",
      result: "Only patches that both parse and pass verification are marked fixed.",
      stack: ["Python", "LLM agents", "MCP"],
      year: "2026",
      links: { code: "https://github.com/SamparkBhol/SecFix" },
      featured: false,
      accent: "#FF8A8A",
      glyph: "shield",
    },
    {
      id: "plumbline",
      name: "Plumbline",
      stamp: "CLAIMS / SOURCES",
      vs: "confident nonsense",
      idea: "Language models make things up. Plumbline checks an answer claim by claim against the sources it was supposed to come from and points at the exact span that backs or contradicts each one.",
      system: "A local-first TypeScript library and CLI. verify(answer, sources) returns a report with a verdict, a confidence, the evidence span per claim and a score; a built-in deterministic engine with no keys and nothing leaving the process, plus an optional transformer engine; guard() wraps any model call with a minimum score.",
      result: "The same answer checked twice gives the same verdict.",
      stack: ["TypeScript", "Node", "Transformers.js"],
      year: "2026",
      links: { code: "https://github.com/SamparkBhol/Plumbline" },
      featured: false,
      accent: "#F3F1EB",
      glyph: "plumb",
    },
    {
      id: "datawiz",
      name: "DataWiz Pro",
      stamp: "AUTOML / BROWSER",
      vs: "the upload step",
      idea: "Privacy-first AutoML and business intelligence for tabular data. Load a file, and it profiles, cleans, selects features, tunes a dozen models and explains the winner, entirely in the browser.",
      system: "CSV, TSV, nested JSON and SQLite ingestion; profiling with distributions and correlations; honest preprocessing you can override per column; outlier detection; a Tree-structured Parzen Estimator search over each model's hyperparameters under cross-validation; explainability dashboards; prediction on new inputs; local projects exported as one portable file.",
      result: "Your data never leaves your machine.",
      stack: ["TypeScript", "React", "in-browser ML"],
      year: "2025",
      links: { live: "https://data-wiz-pro.vercel.app", code: "https://github.com/SamparkBhol/DataWiz-Pro" },
      featured: false,
      accent: "#9BE7FF",
      glyph: "chart",
    },
    {
      id: "phasegraph",
      name: "PhaseGraph",
      stamp: "COMPILER / AGENTS",
      vs: "precision without accuracy",
      idea: "A deterministic compiler and runtime for multi-agent context engineering. Describe agents, artifacts and delivery requirements as a graph; it compiles a scheduled plan under capacity, clearance and budget constraints, executes it against a real corpus, and reconciles what it predicted with what it measured.",
      system: "A static site plus a CLI. No API keys, no server, no database. Real BPE tokenization, real extractive compression, measured digest fidelity, and recalibration of the plan from the measurements.",
      result: "On the bundled example, a delivery that claimed 45% fidelity measured between 3 and 6; recompiling from measured numbers changed the plan itself.",
      stack: ["TypeScript", "static site", "CLI"],
      year: "2026",
      links: { live: "https://phasegraph-3uzy.vercel.app/", code: "https://github.com/SamparkBhol/phasegraph" },
      featured: false,
      accent: "#FFB347",
      glyph: "graph",
    },
    {
      id: "veilcap",
      name: "Veilcap",
      stamp: "TOR / CAPABILITIES",
      vs: "trusting the network",
      idea: "A Tor-native, capability-controlled personal compute network.",
      system: "In development. The repository carries the design; the write-up is next.",
      result: "Early.",
      stack: ["Tor", "capabilities"],
      year: "2026",
      links: { code: "https://github.com/SamparkBhol/Veilcap" },
      featured: false,
      accent: "#B8B2C7",
      glyph: "veil",
    },
  ],

  games: [
    { id: "cli-legend", name: "cli-legend", sub: "roguelike dungeon crawler on npm", year: "2025", href: "https://www.npmjs.com/package/cli-legend", install: "npm i cli-legend", accent: "#FFB347" },
    { id: "pixel-legends", name: "Pixel-legends", sub: "2D retro game hub, live", year: "2025", href: "https://gamehub-gilt.vercel.app/", accent: "#9BE7FF" },
    { id: "zelda", name: "Zelda-like", sub: "a Godot action-adventure", year: "2025", href: "https://github.com/SamparkBhol/Zeldaprojectgame", accent: "#7CE0A5" },
    { id: "gamedev-utils", name: "gamedev-simple-utils", sub: "small utilities for game dev", year: "2025", href: "https://www.npmjs.com/package/gamedev-simple-utils", install: "npm i gamedev-simple-utils", accent: "#C7B8EA" },
    { id: "dev-toolkit", name: "dev-toolkit-sampark", sub: "a CLI toolkit for shipping fast", year: "2025", href: "https://www.npmjs.com/package/dev-toolkit-sampark", install: "npm i dev-toolkit-sampark", accent: "#FF8A8A" },
  ],

  papers: [
    {
      id: "wsn",
      title: "An Energy-Efficient Hybrid Communication Protocol for Large-Area Wireless Sensor Networks",
      venue: "Procedia Computer Science (Elsevier), ICECMSN",
      year: "2025",
      authors: ["Shreyas Karthigeyan", "Sampark Bhol", "Akshat Jain", "Karthik Yadav", "Akash Sinha", "Padma Priya R"],
      authorIndex: 1,
      doi: "10.1016/j.procs.2025.01.059",
      href: "https://www.sciencedirect.com/science/article/pii/S1877050925000596",
      status: "published",
    },
    {
      id: "quantum",
      title: "Hybrid Classical and Quantum Query Complexity for Hypothesis Verification Under Structured Priors and Bounded Phase Noise",
      venue: "Journal submission, with QuantumX",
      year: "2026",
      authors: ["Sampark Bhol"],
      authorIndex: 0,
      status: "under review",
    },
  ],

  posts: [
    { id: "autoresearch", title: "Autoresearch: Automated ML Optimization While You Sleep", href: "https://medium.com/@samparkbhol2005/autoresearch-automated-ml-optimization-while-you-sleep-2880f7b1d390", date: "2026-04-01", words: 1888, tags: ["ML", "agents"], game: "pong" },
    { id: "militarization", title: "The Structured Militarization of Advanced Computing", href: "https://medium.com/@samparkbhol2005/the-structured-militarization-of-advanced-computing-b42e26ffeb2e", date: "2026-02-11", words: 1263, tags: ["computing", "policy"], game: "snake" },
    { id: "models-machines", title: "From Models to Machines: AI and Quantum's Late 2025 to Early 2026 Developments", href: "https://medium.com/@samparkbhol2005/from-models-to-machines-ai-and-quantums-late-2025-to-early-2026-developments-51d12ee707df", date: "2026-02-11", words: 2176, tags: ["AI", "quantum"], game: "breakout" },
    { id: "defence-quantum", title: "Defence Gets Faster, Sharper, and Stronger x Quantum Computing", href: "https://medium.com/@samparkbhol2005/defence-gets-faster-sharper-and-stronger-x-quantum-computing-9830ffabe5ba", date: "2025-12-20", words: 1976, tags: ["quantum"], game: "invaders" },
    { id: "quantai", title: "QUANTAI (Quantum and Tokenized AI Sidechains): opening a possibility in this limitless field of AI", href: "https://medium.com/@samparkbhol2005/quantai-quantum-and-tokenized-ai-sidechains-opening-a-possibility-in-this-limitless-field-of-ai-2092e3b864a3", date: "2025-09-01", words: 843, tags: ["quantum", "blockchain"], game: "runner" },
    { id: "rl-games", title: "Advancing RL in Multimodal Games: Tackling Offline, Continual, and Bias Challenges", href: "https://medium.com/@samparkbhol2005/advancing-rl-in-multimodal-games-tackling-offline-continual-and-bias-challenges-a8b2cb2399b4", date: "2025-08-23", words: 2048, tags: ["RL", "games"], game: "pong" },
    { id: "a2a-mcp", title: "The Rise of Agent Communication: Google's A2A and Anthropic's MCP", href: "https://medium.com/@samparkbhol2005/the-rise-of-agent-communication-googles-a2a-and-anthropic-s-mcp-dd3c7202830b", date: "2025-06-27", words: 1735, tags: ["agents", "MCP"], game: "snake" },
    { id: "neurosymbolic", title: "NeuroSymbolic AI: A View", href: "https://medium.com/@samparkbhol2005/neurosymbolic-ai-a-view-328617188529", date: "2025-05-20", words: 988, tags: ["AI research"], game: "breakout" },
    { id: "quantum-nlp", title: "Quantum-Enhanced NLP: The Future of Cloud AI", href: "https://medium.com/@samparkbhol2005/quantum-enhanced-nlp-the-future-of-cloud-ai-aff15f85f274", date: "2025-03-05", words: 988, tags: ["quantum", "NLP"], game: "invaders" },
    { id: "cern", title: "CERN in October: A Month of Milestones and Marvels", href: "https://medium.com/@samparkbhol2005/cern-in-october-a-month-of-milestones-and-marvels-c289c5c140f3", date: "2024-10-09", words: 1331, tags: ["physics"], game: "runner" },
  ],

  // Episodes are numbered by year earned. The two Oracle credentials currently share one Drive file;
  // replace the Professional link with its own credential when you have it.
  certs: [
    { id: "ibm-dl", ep: 1, title: "IBM Deep Learning Fundamentals", issuer: "IBM (Cognitive Class)", year: "2024", verifyUrl: "https://courses.cognitiveclass.ai/certificates/2752886f81c445d3b1e6a260dd508b57" },
    { id: "saviynt", ep: 2, title: "ISAA Saviynt Identity Security", issuer: "Saviynt", year: "2024", verifyUrl: "https://drive.google.com/file/d/1JIiLKb4FZheMo9TkICBUj9YOqX0DkC70/view" },
    { id: "nvidia", ep: 3, title: "Building Transformer-Based NLP Applications", issuer: "NVIDIA", year: "2025", verifyUrl: "https://drive.google.com/file/d/15jOc2py2i3BwMSgGT2Dsea2fR0EesIMb/view" },
    { id: "oci-assoc", ep: 4, title: "Oracle Cloud Infrastructure Associate", issuer: "Oracle", year: "2025", verifyUrl: "https://drive.google.com/file/d/10oyQhf3rD7HnHv3NYwNhy9JIWIdrOZ24/view" },
    { id: "oci-genai", ep: 5, title: "Oracle Generative AI Cloud Infrastructure Professional", issuer: "Oracle", year: "2025", verifyUrl: "https://drive.google.com/file/d/10oyQhf3rD7HnHv3NYwNhy9JIWIdrOZ24/view" },
  ],

  education: {
    school: "VIT Vellore",
    degree: "B.Tech, Computer Science & Engineering",
    period: "2022 – 2026",
    location: "Vellore, India",
    coursework: ["Data Structures & Algorithms", "Operating Systems", "Database Management Systems", "Computer Networks", "Object-Oriented Programming", "Statistics & Probability", "Linear Algebra"],
  },

  also: [
    { label: "AI/ML lead", text: "IEEE Computer Society, VIT (2023 – 2025): hackathons with 200+ participants, workshops on deep learning, NLP and computer vision." },
    { label: "Member", text: "Association of Energy Engineers (2023 – 2024)." },
    { label: "Off-hours", text: "Browser games, a Godot action-adventure, a roguelike on npm. Games are how I learn game feel." },
  ],

  skills: [
    { id: "lang", group: "Languages & systems", slot: "MAIN HAND", items: [
      { name: "Python", usedAt: ["clr3", "csm", "nic", "quantumx", "cairn", "quark", "secfix"] }, { name: "Go", usedAt: ["helmit"] }, { name: "Java", usedAt: ["helmit"] },
      { name: "TypeScript", usedAt: ["helmit", "shadow-agent", "plumbline", "phasegraph", "datawiz"] }, { name: "JavaScript", usedAt: ["browser-llm", "pixel-legends"] },
      { name: "SQL", usedAt: ["nic", "clr3"] }, { name: "R", usedAt: ["nic"] }, { name: "Microservices", usedAt: ["helmit"] }, { name: "REST APIs", usedAt: ["helmit", "clr3"] },
      { name: "gRPC", usedAt: ["helmit"] }, { name: "System design", usedAt: ["helmit", "cairn", "phasegraph"] },
    ] },
    { id: "ml", group: "AI/ML & generative AI", slot: "SPELLBOOK", items: [
      { name: "PyTorch", usedAt: ["quark"] }, { name: "TensorFlow", usedAt: ["csm"] }, { name: "Keras", usedAt: ["csm"] }, { name: "Scikit-learn", usedAt: ["nic"] },
      { name: "XGBoost", usedAt: ["clr3"] }, { name: "LightGBM", usedAt: ["clr3"] }, { name: "Hugging Face Transformers", usedAt: ["csm", "shadow-agent"] },
      { name: "LangChain", usedAt: ["csm"] }, { name: "LangGraph", usedAt: ["csm"] }, { name: "RAG", usedAt: ["csm"] }, { name: "BERT", usedAt: ["csm"] }, { name: "GPT", usedAt: ["csm"] },
      { name: "LoRA · QLoRA · PEFT", usedAt: ["csm"] }, { name: "Embeddings & semantic search", usedAt: ["clr3", "quark"] }, { name: "NER", usedAt: ["csm"] }, { name: "OpenCV", usedAt: [] },
      { name: "Tool-calling agents", usedAt: ["helmit", "clr3", "cairn", "secfix"] },
    ] },
    { id: "data", group: "Data science, analytics & engineering", slot: "TOOLBELT", items: [
      { name: "Pandas", usedAt: ["nic", "datawiz"] }, { name: "NumPy", usedAt: ["nic"] }, { name: "Matplotlib", usedAt: ["nic"] }, { name: "Seaborn", usedAt: ["nic"] }, { name: "Plotly", usedAt: ["nic", "datawiz"] },
      { name: "Power BI", usedAt: [] }, { name: "Tableau", usedAt: [] }, { name: "A/B testing", usedAt: ["clr3"] }, { name: "Hypothesis testing", usedAt: ["datawiz"] }, { name: "Bayesian inference", usedAt: ["datawiz"] },
      { name: "Feature engineering", usedAt: ["nic", "clr3"] }, { name: "EDA", usedAt: ["nic"] }, { name: "Time series", usedAt: ["clr3"] }, { name: "Kafka", usedAt: ["clr3"] }, { name: "Spark", usedAt: [] },
      { name: "Airflow", usedAt: [] }, { name: "ETL / ELT", usedAt: ["nic"] }, { name: "Data warehousing", usedAt: ["nic"] },
    ] },
    { id: "cloud", group: "Cloud, MLOps & databases", slot: "ARMOR", items: [
      { name: "AWS (S3, Lambda, RDS, SageMaker, Bedrock)", usedAt: ["helmit"] }, { name: "GCP (GKE, Cloud Run, Vertex AI)", usedAt: ["helmit"] }, { name: "Docker", usedAt: ["csm"] }, { name: "Kubernetes", usedAt: ["helmit", "csm"] },
      { name: "Terraform", usedAt: [] }, { name: "GitHub Actions", usedAt: ["helmit", "clr3"] }, { name: "Cloud Build", usedAt: ["helmit"] }, { name: "MLflow", usedAt: [] }, { name: "Kubeflow", usedAt: [] }, { name: "Grafana", usedAt: ["clr3"] },
      { name: "OpenTelemetry", usedAt: ["helmit"] }, { name: "FastAPI", usedAt: [] }, { name: "Node.js", usedAt: ["plumbline"] }, { name: "React", usedAt: ["datawiz", "pixel-legends"] },
      { name: "PostgreSQL", usedAt: ["helmit", "quantumx"] }, { name: "MySQL", usedAt: [] }, { name: "MongoDB", usedAt: [] }, { name: "Redis", usedAt: ["helmit", "clr3"] }, { name: "ClickHouse", usedAt: ["clr3"] },
      { name: "Elasticsearch", usedAt: [] }, { name: "Pinecone", usedAt: ["csm"] }, { name: "ChromaDB", usedAt: ["csm"] }, { name: "FAISS", usedAt: [] }, { name: "RabbitMQ", usedAt: ["quantumx"] },
      { name: "Qiskit", usedAt: ["quark"] }, { name: "QAOA · VQE", usedAt: ["quantumx"] },
    ] },
    { id: "mobile", group: "Mobile, web & games", slot: "OFF HAND", items: [
      { name: "React Native", usedAt: ["helmit"] }, { name: "Expo", usedAt: ["helmit"] }, { name: "Swift bridges", usedAt: ["helmit"] }, { name: "Sentry · PostHog · Firebase", usedAt: ["helmit"] },
      { name: "WebGPU", usedAt: ["browser-llm", "shadow-agent"] }, { name: "Transformers.js", usedAt: ["browser-llm", "shadow-agent"] }, { name: "Next.js", usedAt: ["shadow-agent"] },
      { name: "Godot", usedAt: ["zelda"] }, { name: "Unity", usedAt: [] }, { name: "Game design", usedAt: ["cli-legend", "pixel-legends", "zelda"] },
    ] },
  ],

  classes: [
    {
      id: "software", name: "Software Engineer", tagline: "Services that survive production.", gear: "software",
      blurb: "I like the part of the job nobody screenshots: the timeout that finally propagates, the migration that runs on a Friday and nobody notices. Give me a queue, a database and a pager and I'm happy. If it has to survive real traffic, I want to be the one who built it.",
      roles: ["helmit", "clr3", "quantumx"], projects: ["cairn", "phasegraph", "secfix", "plumbline"],
      stats: [["Migrations shipped", "58"], ["Integrations", "9"], ["Replicas scaled", "3 → 8"], ["Clouds", "AWS · GCP"]],
    },
    {
      id: "ml", name: "AI/ML Engineer", tagline: "Models that hold up in front of real traffic.", gear: "ml",
      blurb: "Notebooks are where ideas are born; production is where they grow up. I train the model, then I build the road it has to drive on: feature stores, caches, tracing, the boring armour. My favourite metric is the one that still holds a month after launch.",
      roles: ["clr3", "csm", "nic", "helmit"], projects: ["datawiz", "cairn", "shadow-agent", "browser-llm"],
      stats: [["Forecast accuracy", "92%"], ["Queries per second", "10K+"], ["Records handled", "1M+"], ["Precision & recall", "95%"]],
    },
    {
      id: "research", name: "Research Enthusiast", tagline: "Questions first, then the code.", gear: "research",
      blurb: "Some evenings I read papers for fun and then ruin the fun by trying to reproduce them. Quantum circuits, hybrid query complexity, sensor networks: I chase the question until it turns into something I can run. The second author line is where the work gets done.",
      roles: ["quantumx", "nic"], projects: ["quark"],
      stats: [["Papers", "1 published · 1 under review"], ["Library", "quark"], ["Model", "647k params"], ["Protocols", "QAOA · VQE"]],
    },
    {
      id: "games", name: "Game Developer", tagline: "Game feel, learned by making games.", gear: "games",
      blurb: "I started with a browser and a keyboard and a level that was far too hard. I still make small games to learn how things feel: a jump that lands, a dash that reads, a boss with a tell. Everything on this page is that habit, pointed at a portfolio.",
      roles: [], projects: ["browser-llm", "shadow-agent"],
      stats: [["Games shipped", "3"], ["npm packages", "3"], ["Live demos", "6"], ["Engines", "Godot · browser"]],
    },
  ],

  // Weekly downloads were read from api.npmjs.org on 2026-09-16; the shop shows them with that date.
  packages: [
    { id: "cli-legend", name: "cli-legend", version: "1.0.0", description: "A command-line roguelike dungeon crawler: ASCII rooms, turn-based combat, an inventory, permadeath.", install: "npm i cli-legend", href: "https://www.npmjs.com/package/cli-legend", tags: ["cli", "roguelike", "game"], weeklyDownloads: 7, checkedOn: "2026-09-16" },
    { id: "gamedev-simple-utils", name: "gamedev-simple-utils", version: "1.0.0", description: "Small utilities for game development: timers, easing, vectors, random tables.", install: "npm i gamedev-simple-utils", href: "https://www.npmjs.com/package/gamedev-simple-utils", tags: ["gamedev", "utils"], weeklyDownloads: 1, checkedOn: "2026-09-16" },
    { id: "dev-toolkit-sampark", name: "dev-toolkit-sampark", version: "1.0.0", description: "A CLI toolkit for shipping fast: scaffolds, checks and small conveniences for everyday dev work.", install: "npm i dev-toolkit-sampark", href: "https://www.npmjs.com/package/dev-toolkit-sampark", tags: ["cli", "toolkit", "dx"], weeklyDownloads: 4, checkedOn: "2026-09-16" },
  ],

  sideQuests: [
    { id: "ieee", org: "IEEE Computer Society, VIT", role: "AI/ML Lead", period: "2023 – 2025", summary: "Led the AI/ML wing: events, workshops and community projects.", rewards: ["Hackathons with 200+ participants", "Workshops on deep learning, NLP and computer vision", "Community projects shipped with students"], status: "complete" },
    { id: "aee", org: "Association of Energy Engineers", role: "Member", period: "2023 – 2024", summary: "Energy-efficiency and sustainability initiatives.", rewards: ["An energy-efficiency research community", "Sustainability-focused collaboration", "The background for the WSN energy paper"], status: "complete" },
    { id: "quark-oss", org: "quark", role: "Open-source maintainer", period: "2026 – ongoing", summary: "quark, the quantum circuit embedding library, is open source and I keep maintaining it. Presented at FITT, IIT Delhi.", rewards: ["Presented at FITT, IIT Delhi", "A pretrained model shipped in the package", "A QASM deduplication CLI", "Qiskit and PennyLane integrations"], status: "ongoing" },
  ],

  contact: {
    openTo: "Backend and platform roles; agent systems",
    where: "Remote, or Munich",
    timezone: "IST, overlaps CET",
    response: "24–48 hours",
  },
};

export default resume;
